### ISSUE TITLE
ddm error if additional_regressors is null

### ISSUE THREAD

**Issue by scharlottej13** [pachamaltese/gravity#14]
Hi!

I hit an error trying to run a simple gravity model without any additional regressors. I tried to implement a fix, but hit some R version issues before I could test: [https://github.com/scharlottej13/gravity/commit/a51891e5cba76400ddbcd9e2f88adf2c51a03898](url)

Thanks in advance for your help.

**Comment by pachadotdev** [comment]
Hi @scharlottej13 
Thanks for opening this issue! Can you provide me a bit more of context about using DDM without additional variables?
I shall check your pull request and merge it. I also plan to add eflm package for fast fitting, please let me know if you have 5 minutes for a quick call if you would like to contribute to gravity.

**Comment by scharlottej13** [comment]
Yes of course, thx for your quick reply! Here's my function call:
`ddm(dependent_variable = "flow", distance = "distance", code_origin = "iso3_orig", code_destination = "iso3_dest", data = select(df, flow, distance, iso3_orig, iso3_dest))`

where `flow` is the number of people who have moved from `iso3_orig` to `iso3_dest`

the error I get is:
Error: Problem with `mutate()` input `key`.
✖ object 'key' not found
ℹ Input `key` is `paste0(key, "_ddm")`.

**Comment by pachadotdev** [comment]
>  `ddm(dependent_variable = "flow", distance = "distance", code_origin = "iso3_orig", code_destination = "iso3_dest", data = select(df, flow, distance, iso3_orig, iso3_dest))`

thanks,  I've followed you on Twitter (@pachamaltese)

**Comment by pachadotdev** [comment]
merged ! it passes all tests
