### ISSUE TITLE
Error: Can't subset columns that don't exist. ✖ Column `y_log_ddm,` doesn't exist.

### ISSUE THREAD

**Issue by scharlottej13** [pachamaltese/gravity#17]
was able to test it this time, worked w/ this fix! #16

**Comment by pachadotdev** [comment]
Thanks!! It passed the tests anyways.
I shall run a manual test to be sure.
When are you available to talk about the new gravity version?

**Comment by scharlottej13** [comment]
perfect, thank you! and I'll DM you on twitter and let you know my availability

**Comment by pachadotdev** [comment]
fixed in #15
