### ISSUE TITLE
consistent formula expression across functions

### ISSUE THREAD

**Issue by pachadotdev** [pachamaltese/gravity#3]
some functions as `BVU` use the elegant `lm(Y ~ ., data = gravity)` while others use this weirdness
```r
form <- stats::as.formula(paste("y_log_rat", "~ dist_log_rat +", paste(additional_regressors, collapse = " + ")))
```
something better should be used !!!!!

**Comment by jbkunst** [comment]
We can filter the columns before the `lm`.

```r
gravity <- filter(gravity, only_columns_to_use_in_lm)
# then
lm(Y ~ ., data = gravity)
```

**Comment by pachadotdev** [comment]
not really as vcov uses the iso codes as input, but I found a decent way ;)
