### ISSUE TITLE
documentation typo

### ISSUE THREAD

**Issue by DiegoKoz** [pachamaltese/gravity#6]
Hi! I'm copying some previous comments. 

in the documentation of the functions, the `regressors` param, it says "curreny", I think it is repeated in all the functions. 

_Originally posted by @DiegoKoz in https://github.com/openjournals/joss-reviews/issues/926#issuecomment-428302360_

**Comment by DiegoKoz** [comment]
I see this is already corrected

**Comment by pachadotdev** [comment]
thanks @DiegoKoz 
it was already fixed around https://github.com/pachamaltese/gravity/tree/8c8ab898a9c84a532e57a6ce640df131beafe025
